

export const CHANGE_INPUTVALUE = 'CHANGE_INPUTVALUE'
export const SEARCH_INPUTVALUE = 'SEARCH_INPUTVALUE'
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA'
export const FETCH_INITIAL_DATA_FUFILLED = 'FETCH_INITIAL_DATA_FUFILLED'
export const FETCH_INITIAL_DATA_FAILED = 'FETCH_INITIAL_DATA_FAILED';
